### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by kolisko** [espocrm/espocrm#1080]
Any plan to implement Dockerfile?

**Comment by yurikuzn** [comment]
Yes.

**Comment by karthik-uc** [comment]
Hi @kolisko, @tmachyshyn

I have implemented espocrm in docker for my organisation. You can use it as a reference if you'd like to use it.

https://github.com/thebuzzycoder/dockerised-espocrm

**Comment by bandtank** [comment]
How did you handle the upload directory?

**Comment by karthik-uc** [comment]
Hi @bandtank,

In above question, did you mean adding extensions and integrations like VoIP and Advanced packs?

If so, I have a good solution which is already implemented for the extensions. But I haven't updated my repository, yet. Will update it by next 2 days and let you know once I am ready with it.

**Comment by bandtank** [comment]
@karthik-uc No, I mean where do you store uploads and how do you make sure each docker instance has access to the files?

**Comment by karthik-uc** [comment]
@bandtank 

The dockerfile has 3 stage build (See Dockerfile)

1. First I download the source code from git repository for the required version of EspoCRM which I pass as --build-args docker build option using wget. And immediately after I run composer install on it.
2. Next I copy the files from previous stage to current one and then, I create the build directory using npm and grunt.
3. I copy the directory from the stage-2 build to last stage which will create an image.

So, when you run the image each container will have required files in it. Now, the things that are needed to be common across containers is database and config.php which I store it in docker volumes (See prod.docker-compose.yml).

**Comment by bandtank** [comment]
@karthik-uc  That's not what I mean. You're talking about build, but I assumed build worked already. When you upload a file into the CRM, the file is stored in data/uploads, so it is only available to the instance that uploaded it unless you are sharing the uploads directory between docker instances. This is a functionality problem, not a build problem.

If the files are stored in S3 or shared between instances by the docker host, then it's probably fine, but it's not clear how you're handling this. If one instance uploads a file, it will be shown in the GUI to all instances even if the file isn't available because the filename and link are from the database, not the disk.

**Comment by karthik-uc** [comment]
The entire data directory is mounted to a docker volume.
```
  webserver:
    container_name: crmServer
    image: crm-webapp:1.0.0
    build:
      context: .
      dockerfile: webapp/project1/Dockerfile
      args:
        VERSION: ${espo}
    ports:
      - 80:80
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html
      DB_HOST: ${mysql_host}
      DB_USER: ${mysql_user}
      DB_PASSWORD: ${mysql_passwd}
      DB_NAME: ${mysql_db}
      DB_DRIVER: mysqldb:mysql
    links:
      - mysqldb:mysql
    volumes:
      - database-configurations:/crm/espocrm/data
    command: "nginx -g 'daemon off;'"
```

**Comment by theBuzzyCoder** [comment]
Regarding https://github.com/espocrm/espocrm/issues/1080#issuecomment-441574705

As promised, ability to add extension is also added to folder addons. Again this is just a suggested architecture and not a maintained code. So, please take what you need from it and maintain your code separately. 

**Do Not Fork or Clone as it is not maintained**

**Comment by whalehub** [comment]
@tmachyshyn Any update on this? Having a Docker image would be nice because it allows you to deploy EspoCRM consistently.

**Comment by tmachyshyn** [comment]
This is not implemented yet.

**Comment by karthik-uc** [comment]
@tmachyshyn @yurikuzn 

Any rough idea on when will this be implemented? Timelines/roadmap?

**Comment by whalehub** [comment]
@karthik-uc I ended up making my own Docker image in the meantime: [graywhale/espocrm](https://hub.docker.com/r/graywhale/espocrm)

Here's my Docker Compose file for it:

```yaml
version: '3.7'

services:
  espocrm:
    image: graywhale/espocrm
    container_name: espocrm
    hostname: espocrm
    restart: unless-stopped
    depends_on:
      - mariadb-espocrm
    volumes:
      - /opt/docker/espocrm:/var/www/espocrm/data
    networks:
      proxy:
        ipv4_address: 172.20.0.10
  mariadb-espocrm:
    image: mariadb
    container_name: mariadb-espocrm
    hostname: mariadb-espocrm
    restart: unless-stopped
    volumes:
      - /opt/docker/mariadb-espocrm:/var/lib/mysql
    networks:
      proxy:
        ipv4_address: 172.20.0.11
    environment:
      - MYSQL_ROOT_PASSWORD=<redacted>
      - MYSQL_DATABASE=espocrm
      - MYSQL_USER=espocrm
      - MYSQL_PASSWORD=<redacted>

networks:
  proxy:
    external:
      name: proxy
```
