### ISSUE TITLE
Error while performing creating/updating roles with AWS S3 configured as the file storage

### ISSUE THREAD

**Issue by praveen-kumar85** [espocrm/espocrm#2759]
**Describe the bug**
I've tried playing around with roles with my admin user and things were working fine. Later after configuring AWS S3 as the file storage, I'm getting 500 error while updating the role. I'm not sure what exactly is the connection here. The S3 storage settings are working fine as I'm able to update the avatar of the admin user and I can see that the image is uploaded to S3 bucket..

**To Reproduce**
1. Setup AWS S3 as the file storage
2. Try creating a role with some permissions enabled

**Expected behavior**
Role should be saved without any error.

**Screenshots**
Error while creating the role.
<img width="1012" alt="Screenshot 2023-06-03 at 12 44 04 AM" src="https://github.com/espocrm/espocrm/assets/108792451/62485e4e-4555-4ceb-ad73-e6c0dfb6aadf">

File successfully uploaded to S3
<img width="1353" alt="Screenshot 2023-06-03 at 12 43 08 AM" src="https://github.com/espocrm/espocrm/assets/108792451/c51e8baa-ceee-4fe8-a671-0052fa4d3143">

**EspoCRM version**
7.4.6

**Comment by yurikuzn** [comment]
Error from the log would be helpful. With print trace enabled. https://docs.espocrm.com/administration/log/#trace-printing

**Comment by yurikuzn** [comment]
Could not reproduce. No error.

**Comment by praveen-kumar85** [comment]
> [2023-06-02 19:33:17] ERROR: (0) Could not save config.; PUT /Role/647a3e7a154efefee; line: 199, file: /var/www/html/application/Espo/Core/Utils/Config/ConfigWriter.php :: #0 /var/www/html/application/Espo/Core/Utils/Config/ConfigWriter.php(180): Espo\Core\Utils\Config\ConfigWriter->saveData('data/config.php', Array, 'microtime') #1 /var/www/html/application/Espo/Core/DataManager.php(179): Espo\Core\Utils\Config\ConfigWriter->save() #2 /var/www/html/application/Espo/Services/Role.php(66): Espo\Core\DataManager->updateCacheTimestamp() #3 /var/www/html/application/Espo/Services/Role.php(59): Espo\Services\Role->clearRolesCache() #4 /var/www/html/application/Espo/Core/Record/Service.php(751): Espo\Services\Role->afterUpdateEntity(Object(Espo\Entities\Role), Object(stdClass)) #5 /var/www/html/application/Espo/Core/Controllers/RecordBase.php(231): Espo\Core\Record\Service->update('647a3e7a154efef...', Object(stdClass), Object(Espo\Core\Record\UpdateParams)) #6 /var/www/html/application/Espo/Core/Api/ControllerActionProcessor.php(87): Espo\Core\Controllers\RecordBase->putActionUpdate(Object(Espo\Core\Api\RequestWrapper), Object(Espo\Core\Api\ResponseWrapper)) #7 /var/www/html/application/Espo/Core/Api/ControllerActionHandler.php(69): Espo\Core\Api\ControllerActionProcessor->process('Role', 'update', Object(Espo\Core\Api\RequestWrapper), Object(Espo\Core\Api\ResponseWrapper)) #8 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Espo\Core\Api\ControllerActionHandler->handle(Object(Slim\Psr7\Request)) #9 /var/www/html/application/Espo/Core/Api/RouteProcessor.php(222): Slim\MiddlewareDispatcher->handle(Object(Slim\Psr7\Request)) #10 /var/www/html/application/Espo/Core/Api/RouteProcessor.php(149): Espo\Core\Api\RouteProcessor->processControllerAction(Object(Espo\Core\Api\ProcessData), Object(Slim\Psr7\Request), Object(Espo\Core\Api\ResponseWrapper)) #11 /var/www/html/application/Espo/Core/Api/RouteProcessor.php(127): Espo\Core\Api\RouteProcessor->processAfterAuth(Object(Espo\Core\Api\ProcessData), Object(Slim\Psr7\Request), Object(Espo\Core\Api\ResponseWrapper)) #12 /var/www/html/application/Espo/Core/Api/RouteProcessor.php(79): Espo\Core\Api\RouteProcessor->processInternal(Object(Espo\Core\Api\ProcessData), Object(Slim\Psr7\Request), Object(Espo\Core\Api\RequestWrapper), Object(Espo\Core\Api\ResponseWrapper)) #13 /var/www/html/application/Espo/Core/Api/Starter.php(109): Espo\Core\Api\RouteProcessor->process(Object(Espo\Core\Api\ProcessData), Object(Slim\Psr7\Request), Object(Slim\Psr7\Response)) #14 /var/www/html/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(38): Espo\Core\Api\Starter->Espo\Core\Api\{closure}(Object(Slim\Psr7\Request), Object(Slim\Psr7\Response), Array) #15 /var/www/html/vendor/slim/slim/Slim/Routing/Route.php(358): Slim\Handlers\Strategies\RequestResponse->__invoke(Object(Closure), Object(Slim\Psr7\Request), Object(Slim\Psr7\Response), Array) #16 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\Routing\Route->handle(Object(Slim\Psr7\Request)) #17 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\MiddlewareDispatcher->handle(Object(Slim\Psr7\Request)) #18 /var/www/html/vendor/slim/slim/Slim/Routing/Route.php(315): Slim\MiddlewareDispatcher->handle(Object(Slim\Psr7\Request)) #19 /var/www/html/vendor/slim/slim/Slim/Routing/RouteRunner.php(68): Slim\Routing\Route->run(Object(Slim\Psr7\Request)) #20 /var/www/html/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(45): Slim\Routing\RouteRunner->handle(Object(Slim\Psr7\Request)) #21 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\RoutingMiddleware->process(Object(Slim\Psr7\Request), Object(Slim\Routing\RouteRunner)) #22 /var/www/html/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(Slim\Psr7\Request)) #23 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\ErrorMiddleware->process(Object(Slim\Psr7\Request), Object(Psr\Http\Server\RequestHandlerInterface@anonymous)) #24 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(Slim\Psr7\Request)) #25 /var/www/html/vendor/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher->handle(Object(Slim\Psr7\Request)) #26 /var/www/html/vendor/slim/slim/Slim/App.php(183): Slim\App->handle(Object(Slim\Psr7\Request)) #27 /var/www/html/application/Espo/Core/Api/Starter.php(76): Slim\App->run() #28 /var/www/html/application/Espo/Core/ApplicationRunners/Api.php(45): Espo\Core\Api\Starter->start() #29 /var/www/html/application/Espo/Core/Application/RunnerRunner.php(87): Espo\Core\ApplicationRunners\Api->run() #30 /var/www/html/application/Espo/Core/Application.php(78): Espo\Core\Application\RunnerRunner->run('Espo\\Core\\Appli...', NULL) #31 /var/www/html/public/api/v1/index.php(37): Espo\Core\Application->run('Espo\\Core\\Appli...') #32 {main} 

This is the error log.

**Comment by yurikuzn** [comment]
Config saved does not utilize the file storage framework. AWS configured should be the cause of your problem.

**Comment by yurikuzn** [comment]
I recommend debugging. Print the exception message.

**Comment by praveen-kumar85** [comment]
@yurikuzn I could be wrong in assuming that storage is causing the issue. But the error is still showing up. Please check the stack trace.

**Comment by yurikuzn** [comment]
I'm too busy.

**Comment by praveen-kumar85** [comment]
I am able to reproduce the issue. I've installed the application via docker and configured the DB in a separate MySQL container. After that, I've noted the passwordSalt, cryptKey, hashSecretKey generated. I stopped the current container and created a new container (I've skipped the installation process this time) with these values for passwordSalt, cryptKey, hashSecretKey via environment variables. Any suggestions to reuse the passwordSalt, cryptKey, hashSecretKey values for a given DB instance so that multiple docker containers can access the same DB?

This is similar to https://github.com/espocrm/espocrm-docker/issues/9.

**Comment by digitalextremist** [comment]
@praveen-kumar85 do you mind reformatting your log above inside a preformatted code block? Will try to help if I can to take some load off @yurikuzn. I am not using `S3` but I am using `docker` extensively, and considering trying to use `S3` compatible `DigitalOcean Spaces` down the line. Can lend another set of eyes that might help since I seem to be a lightning rod right now, picking up similar issues with the `docker` implementation.

**Comment by praveen-kumar85** [comment]
@digitalextremist I've formatted the error log.

**Comment by digitalextremist** [comment]
Thanks @praveen-kumar85 

Do your `Permissions` show Writable/green in `Administration > System Requirements`?

Can you also post your `docker-compose.yml`?

**Comment by praveen-kumar85** [comment]
<img width="1502" alt="Screenshot 2023-06-03 at 9 13 10 AM" src="https://github.com/espocrm/espocrm/assets/108792451/ed203a2b-802c-4115-b87e-b259dfa1cfd6">
All the permissions are in green.

Please check the docker-compose.yml file content below. Please check that ESPOCRM_CONFIG_IS_INSTALLED is set to true to avoid reinstalling the application. And I've explicitly set the values for `passwordSalt, cryptKey, hashSecretKey`.

```yaml
version: '3.8'

services:

  mysql:
    image: mysql:8
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password    
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: espocrm
      MYSQL_USER: espocrm
      MYSQL_PASSWORD: database_password
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306

  espocrm:
    image: customized-espocrm-that-creates-config-php-using-env-variables:latest
    container_name: espocrm
    environment:
      ESPOCRM_DATABASE_HOST: mysql
      ESPOCRM_DATABASE_USER: espocrm
      ESPOCRM_DATABASE_PASSWORD: database_password
      ESPOCRM_ADMIN_USERNAME: admin
      ESPOCRM_ADMIN_PASSWORD: password
      ESPOCRM_SITE_URL: "http://localhost:8080"
      ESPOCRM_CONFIG_THUMB_IMAGE_CACHE_DISABLED: true
      ESPOCRM_CONFIG_IS_INSTALLED: true
      ESPOCRM_CONFIG_PASSWORD_SALT: afd85d3aef30f582
      ESPOCRM_CONFIG_CRYPT_KEY: 861bf1210b75f7705e48004d7ca0f441
      ESPOCRM_CONFIG_HASH_SECRET_KEY: 223ecea48f0a7e4b7af31ab9e396b2dd
#    volumes:
#      - espocrm:/var/www/html
    restart: always
    ports:
      - 8080:80

#  espocrm-daemon:
#    image: espocrm/espocrm
#    container_name: espocrm-daemon
#    volumes:
#      - espocrm:/var/www/html
#    restart: always
#    entrypoint: docker-daemon.sh
#
#  espocrm-websocket:
#    image: espocrm/espocrm
#    container_name: espocrm-websocket    
#    environment:
#      ESPOCRM_CONFIG_USE_WEB_SOCKET: "true"
#      ESPOCRM_CONFIG_WEB_SOCKET_URL: "ws://localhost:8081"
#      ESPOCRM_CONFIG_WEB_SOCKET_ZERO_M_Q_SUBSCRIBER_DSN: "tcp://*:7777"
#      ESPOCRM_CONFIG_WEB_SOCKET_ZERO_M_Q_SUBMISSION_DSN: "tcp://espocrm-websocket:7777"
#    volumes:
#      - espocrm:/var/www/html
#    restart: always
#    entrypoint: docker-websocket.sh
#    ports:
#      - 8081:8080

volumes:
  mysql:
#  espocrm:

```
